"""
schema_setup.py – Define and create the Milvus collection schema.

Schema design rationale
───────────────────────
Scalar (filterable) fields
  • country          VARCHAR  – keyword filter  (e.g. filter='country == "Germany"')
  • year             INT64    – range / equality filter (e.g. year == 2026)
  • last_date        VARCHAR  – stored as ISO string; filter by string comparison
  • university       VARCHAR  – keyword filter
  • field_of_study   VARCHAR  – keyword filter

Full-text / BM25 field
  • searchable_text  VARCHAR  – concatenation of all metadata; enable_analyzer=True
                               Milvus auto-generates sparse_vector via BM25 Function

Vector fields
  • dense_vector     FLOAT_VECTOR  – semantic embedding (sentence-transformers)
  • sparse_vector    SPARSE_FLOAT_VECTOR – BM25 sparse embedding (auto-generated)

Other stored fields
  • id               INT64 (primary, auto_id)
  • title            VARCHAR
  • link             VARCHAR
  • description      VARCHAR  – human-readable description (stored, not indexed)
"""

from pymilvus import (
    MilvusClient,
    DataType,
    Function,
    FunctionType,
)
from config import (
    MILVUS_URI,
    COLLECTION_NAME,
    DENSE_DIM,
    DENSE_INDEX_TYPE,
    DENSE_METRIC_TYPE,
    SPARSE_INDEX_TYPE,
    SPARSE_METRIC_TYPE,
    SEARCHABLE_TEXT_FIELD,
)


def get_client() -> MilvusClient:
    """Return a connected MilvusClient (Lite or server)."""
    return MilvusClient(uri=MILVUS_URI)


def create_collection(client: MilvusClient, drop_if_exists: bool = False) -> None:
    """Build schema, indexes, and create the scholarships collection."""

    if client.has_collection(COLLECTION_NAME):
        if drop_if_exists:
            client.drop_collection(COLLECTION_NAME)
            print(f"[schema] Dropped existing collection '{COLLECTION_NAME}'.")
        else:
            print(f"[schema] Collection '{COLLECTION_NAME}' already exists – skipping creation.")
            return

    # ── 1. Schema ──────────────────────────────────────────────────────────────
    schema = client.create_schema(auto_id=True, enable_dynamic_field=False)

    # Primary key (auto-generated)
    schema.add_field("id", DataType.INT64, is_primary=True, description="Auto ID")

    # ── Scalar / filterable fields ─────────────────────────────────────────────
    schema.add_field(
        "title", DataType.VARCHAR, max_length=512,
        description="Scholarship name",
    )
    schema.add_field(
        "country", DataType.VARCHAR, max_length=128,
        description="Target country for the scholarship",
    )
    schema.add_field(
        "university", DataType.VARCHAR, max_length=256,
        description="Offering university / institution",
    )
    schema.add_field(
        "field_of_study", DataType.VARCHAR, max_length=256,
        description="Academic field / discipline",
    )
    schema.add_field(
        "year", DataType.INT64,
        description="Application / study year",
    )
    schema.add_field(
        "last_date", DataType.VARCHAR, max_length=64,
        description="Application deadline (ISO date string YYYY-MM-DD)",
    )
    schema.add_field(
        "link", DataType.VARCHAR, max_length=1024,
        description="Official scholarship URL",
    )
    schema.add_field(
        "description", DataType.VARCHAR, max_length=4096,
        description="Human-readable scholarship description (stored only)",
    )

    # ── Full-text / BM25 field ─────────────────────────────────────────────────
    # enable_analyzer=True lets Milvus tokenise the text for BM25 scoring.
    schema.add_field(
        SEARCHABLE_TEXT_FIELD, DataType.VARCHAR, max_length=8192,
        enable_analyzer=True,
        description="Concatenated text for BM25 full-text search",
    )

    # ── Vector fields ──────────────────────────────────────────────────────────
    schema.add_field(
        "dense_vector", DataType.FLOAT_VECTOR, dim=DENSE_DIM,
        description="Dense semantic embedding",
    )
    schema.add_field(
        "sparse_vector", DataType.SPARSE_FLOAT_VECTOR,
        description="BM25 sparse embedding (auto-generated by Milvus Function)",
    )

    # ── 2. BM25 Function: searchable_text → sparse_vector ─────────────────────
    bm25_fn = Function(
        name="bm25_scholarship",
        function_type=FunctionType.BM25,
        input_field_names=[SEARCHABLE_TEXT_FIELD],
        output_field_names=["sparse_vector"],
    )
    schema.add_function(bm25_fn)

    # ── 3. Index parameters ────────────────────────────────────────────────────
    index_params = client.prepare_index_params()

    # Dense vector index
    index_params.add_index(
        field_name="dense_vector",
        index_name="dense_idx",
        index_type=DENSE_INDEX_TYPE,
        metric_type=DENSE_METRIC_TYPE,
    )

    # Sparse (BM25) vector index
    index_params.add_index(
        field_name="sparse_vector",
        index_name="sparse_idx",
        index_type=SPARSE_INDEX_TYPE,
        metric_type=SPARSE_METRIC_TYPE,
    )

    # Scalar indexes for fast filtering
    for field in ("country", "year", "university", "field_of_study"):
        index_params.add_index(field_name=field, index_type="Trie" if field != "year" else "STL_SORT")

    # ── 4. Create collection ───────────────────────────────────────────────────
    client.create_collection(
        collection_name=COLLECTION_NAME,
        schema=schema,
        index_params=index_params,
    )
    print(f"[schema] Collection '{COLLECTION_NAME}' created successfully.")
    print(f"[schema] Fields: id, title, country, university, field_of_study, "
          f"year, last_date, link, description, {SEARCHABLE_TEXT_FIELD}, "
          f"dense_vector, sparse_vector")
